[project]
name = "lookyloo"
version = "1.28.0"
description = "Web interface to track the trackers."
authors = [{name="Raphaël Vinot", email="raphael.vinot@circl.lu"}]
license = "BSD-3-Clause"
repository = "https://github.com/Lookyloo/lookyloo"
homepage = "https://www.lookyloo.eu"
documentation = "https://www.lookyloo.eu/docs/main/"
requires-python = ">=3.9.2,<3.14"

readme = "README.md"

dynamic = [ "dependencies", "classifiers" ]

[tool.poetry]
classifiers = [
    'Intended Audience :: Science/Research',
    'Intended Audience :: Telecommunications Industry',
    'Intended Audience :: Information Technology',
    'Topic :: Security',
    'Topic :: Internet'
]


[project.scripts]
start = "bin.start:main"
stop = "bin.stop:main"
update = "bin.update:main"
shutdown = "bin.shutdown:main"
run_backend = "bin.run_backend:main"
async_capture = "bin.async_capture:main"
background_indexer = "bin.background_indexer:main"
background_build_captures = "bin.background_build_captures:main"
background_full_indexer = "bin.background_indexer:main_full_indexer"
archiver = "bin.archiver:main"
processing = "bin.background_processing:main"
start_website = "bin.start_website:main"
scripts_controller = "bin.scripts_controller:main"


[tool.poetry.dependencies]
requests = "^2.32.3"
flask = "^3.1.0"
gunicorn = {version = "^23.0.0", extras = ["setproctitle"]}
charset-normalizer = "^3.4.1"
redis = {version = "^5.2.1", extras = ["hiredis"]}
beautifulsoup4 = {version = "^4.13.3", extras = ["lxml", "charset_normalizer"]}
bootstrap-flask = "^2.4.1"
defang = "^0.5.3"
vt-py = "^0.19.0"
pyeupi = "^1.3.0"
pysanejs = "^2.0.4"
pylookyloo = "^1.28.0"
dnspython = "^2.7.0"
pytaxonomies = "^2.0"
pymisp = {version = "^2.5.7.1", extras = ["fileobjects"]}
Pillow = "^11.1.0"
flask-restx = "^1.3.0"
rich = "^13.9.4"
pyphishtanklookup = "^1.4.1"
Flask-Cors = "^5.0.1"
pyhashlookup = "^1.2.6"
lief = "^0.16.4"
ua-parser = {extras = ["regex"], version = "^1.0.1"}
Flask-Login = "^0.6.3"
har2tree = "^1.28.0"
werkzeug = "^3.1.3"
filetype = "^1.2.0"
pypandora = "^1.9.2"
lacuscore = "^1.13.0"
pylacus = "^1.13.0"
pyipasnhistory = "^2.1.4"
publicsuffixlist = "^1.0.2.20250302"
pyfaup = "^1.2"
chardet = "^5.2.0"
pysecuritytxt = "^1.3.3"
pylookyloomonitoring = "^1.1.4"
s3fs = "^2025.2.0"
urllib3 = [
    {version = "<2", python = "<3.10"},
    {version = "^2.3", python = ">=3.10"}
]
pypdns = "^2.2.8"
mmh3 = "^5.1.0"
puremagic = "^1.28"
psutil = "^7.0.0"
flask-talisman = "^1.1.0"

aiohttp = {extras = ["speedups"], version = "^3.11.13"}
pyail = "^0.0.8"

[tool.poetry.group.dev.dependencies]
mypy = "^1.15.0"
ipython = [
    {version = "^9", python = ">=3.11"}
]
types-requests = [
    {version = "<2.32", python = "<3.10"},
    {version = "^2.32", python = ">=3.10"}
]
types-redis = {version = "^4.6.0.20241004"}
types-Deprecated = "^1.2.15.20241117"
types-python-dateutil = "^2.9.0.20241206"
types-beautifulsoup4 = "^4.12.0.20250204"
types-Pillow = "^10.2.0.20240822"
types-pytz = "^2025.1.0.20250204"
types-psutil = "^7.0.0.20250218"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
